{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "investlab-app.serviceAccountName" . }}
  labels:
    {{- include "investlab-app.labels" . | nindent 4 }}
{{- end }}