apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-auth
  namespace: minio
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: minio-auth
    creationPolicy: Owner
    template:
      data:
        rootUser: "{{ .rootUser }}"
        rootPassword: "{{ .rootPassword }}"
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-access-key
    - secretKey: rootPassword
      remoteRef:
        key: minio-secret-key
