apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-auth
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: minio-auth
    creationPolicy: Owner
    template:
      data:
        root-user: "{{ .rootUser }}"
        root-password: "{{ .rootPassword }}"
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-root-user
    - secretKey: rootPassword
      remoteRef:
        key: minio-root-password
