apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth
  namespace: redis
  labels:
    name: redis-auth
    argocd.argoproj.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: redis-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        redis-password: "{{ .redis-password }}"
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis-password