apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-frankfurt-1.enust5kgaacjk.abtheljrpxljsmbjhu5dlo4zxdfjhq7nip7al2dy7zogsacdrcrrd23p2itq
      region: eu-frankfurt-1
      auth:
        instancePrincipal: {}
