apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-frankfurt-1.enusuceeaadwa.abtheljr7c4mvuqlo5dogw3uth6n7st6sosft4pm7vtgepvtxih2m6qys3ua
      region: eu-frankfurt-1
      principalType: InstancePrincipal
